-- m1-backend-skeleton V1 初始迁移（up）
-- 依据：.harness/wiki/data-model.md 表清单（用户确认全量 13 张）+ 旧 FastAPI 模型字段 + PRD §7.2
-- 命名规则：ix_{table}_{col} / uk_{table}_{col} / fk_{table}_{col}
-- garden_plants 无任何来源明细（wiki 仅一句话），按最小合理集建空表，待茶园切片确认后追加迁移

-- users（用户）
CREATE TABLE users (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username         VARCHAR(50)  NOT NULL,
    display_name     VARCHAR(100),
    hashed_password  VARCHAR(200),
    level            INTEGER      NOT NULL DEFAULT 1,
    xp               INTEGER      NOT NULL DEFAULT 0,
    preferred_type   VARCHAR(20),
    preferred_temp   INTEGER,
    preferred_aroma  JSONB        NOT NULL DEFAULT '[]'::jsonb,
    preferred_ware_id INTEGER,
    created_at       TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at       TIMESTAMP    NOT NULL DEFAULT now()
);
COMMENT ON TABLE users IS '用户账户（茶修等级/偏好画像）';
CREATE UNIQUE INDEX uk_users_username ON users (username);

-- tea_regions（茶山产区）
CREATE TABLE tea_regions (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    province   VARCHAR(50),
    city       VARCHAR(50),
    latitude   DOUBLE PRECISION,
    longitude  DOUBLE PRECISION,
    altitude   VARCHAR(50),
    climate    VARCHAR(200),
    soil       VARCHAR(200),
    history    TEXT,
    famous_for JSONB NOT NULL DEFAULT '[]'::jsonb,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);
COMMENT ON TABLE tea_regions IS '茶山产区';

-- tea_processes（制茶工艺）
CREATE TABLE tea_processes (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tea_category VARCHAR(20) NOT NULL,
    name        VARCHAR(100),
    summary     TEXT,
    steps       JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at  TIMESTAMP NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP NOT NULL DEFAULT now()
);
COMMENT ON TABLE tea_processes IS '制茶工艺（六大茶类）';

-- teas（茶叶主表）
CREATE TABLE teas (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(100) NOT NULL,
    category           VARCHAR(20)  NOT NULL,
    origin             VARCHAR(200),
    region_id          INTEGER,
    process_id         INTEGER,
    season             VARCHAR(50),
    grade              VARCHAR(50),
    altitude           VARCHAR(50),
    best_temp          INTEGER,
    best_time          INTEGER,
    infusions          INTEGER NOT NULL DEFAULT 3,
    flavor             JSONB NOT NULL DEFAULT '[]'::jsonb,
    story              TEXT,
    description        TEXT,
    historical_period  VARCHAR(100),
    water_requirement  VARCHAR(100),
    soup_color_min     VARCHAR(20),
    soup_color_max     VARCHAR(20),
    dry_tea_color      VARCHAR(20),
    created_at         TIMESTAMP NOT NULL DEFAULT now(),
    updated_at         TIMESTAMP NOT NULL DEFAULT now()
);
COMMENT ON TABLE teas IS '茶叶主表（六大茶类/冲泡参数/文化故事）';
CREATE INDEX ix_teas_category ON teas (category);
CREATE INDEX ix_teas_region_id ON teas (region_id);
CREATE INDEX ix_teas_process_id ON teas (process_id);
ALTER TABLE teas ADD CONSTRAINT fk_teas_region_id FOREIGN KEY (region_id) REFERENCES tea_regions (id);
ALTER TABLE teas ADD CONSTRAINT fk_teas_process_id FOREIGN KEY (process_id) REFERENCES tea_processes (id);

-- tea_people（茶人历史）
CREATE TABLE tea_people (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(100) NOT NULL,
    dynasty        VARCHAR(50),
    title          VARCHAR(100),
    identity       VARCHAR(100),
    description    TEXT,
    contribution   TEXT,
    quote          TEXT,
    avatar         VARCHAR(50),
    related_tea_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at     TIMESTAMP NOT NULL DEFAULT now(),
    updated_at     TIMESTAMP NOT NULL DEFAULT now()
);
COMMENT ON TABLE tea_people IS '茶人历史';

-- tea_poems（茶诗词）
CREATE TABLE tea_poems (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(200),
    author          VARCHAR(100),
    dynasty         VARCHAR(50),
    content         TEXT,
    related_tea_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    description     TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP NOT NULL DEFAULT now()
);
COMMENT ON TABLE tea_poems IS '茶诗词';

-- teawares（茶器）
CREATE TABLE teawares (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    ware_type     VARCHAR(20),
    material      VARCHAR(100),
    capacity      INTEGER,
    origin        VARCHAR(100),
    dynasty       VARCHAR(50),
    craft         VARCHAR(200),
    description   TEXT,
    culture_story TEXT,
    bonus         JSONB NOT NULL DEFAULT '{}'::jsonb,
    recommended   JSONB NOT NULL DEFAULT '[]'::jsonb,
    rarity        VARCHAR(20) NOT NULL DEFAULT 'common',
    created_at    TIMESTAMP NOT NULL DEFAULT now(),
    updated_at    TIMESTAMP NOT NULL DEFAULT now()
);
COMMENT ON TABLE teawares IS '茶器';

-- tea_etiquettes（茶礼）
CREATE TABLE tea_etiquettes (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    occasion    VARCHAR(100),
    description TEXT,
    steps       JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at  TIMESTAMP NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP NOT NULL DEFAULT now()
);
COMMENT ON TABLE tea_etiquettes IS '茶礼';

-- tea_relations（知识图谱关系）
CREATE TABLE tea_relations (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type  VARCHAR(50),
    source_id    INTEGER,
    target_type  VARCHAR(50),
    target_id    INTEGER,
    relation     VARCHAR(100),
    created_at   TIMESTAMP NOT NULL DEFAULT now(),
    updated_at   TIMESTAMP NOT NULL DEFAULT now()
);
COMMENT ON TABLE tea_relations IS '知识图谱关系';

-- tasting_records（品鉴记录，幂等键 user_id + client_id）
CREATE TABLE tasting_records (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        INTEGER,
    client_id      VARCHAR(64) NOT NULL,
    tea_id         INTEGER,
    tea_name       VARCHAR(100) NOT NULL,
    brew_temp      INTEGER,
    brew_time      INTEGER,
    infusions      INTEGER NOT NULL DEFAULT 1,
    water_type     VARCHAR(20),
    ware_id        INTEGER,
    dimensions     JSONB NOT NULL DEFAULT '{}'::jsonb,
    overall_score  DOUBLE PRECISION,
    process_factor DOUBLE PRECISION,
    aroma_type     VARCHAR(50),
    notes          TEXT,
    weather        VARCHAR(50),
    mood           VARCHAR(50),
    created_at     TIMESTAMP NOT NULL DEFAULT now(),
    updated_at     TIMESTAMP NOT NULL DEFAULT now()
);
COMMENT ON TABLE tasting_records IS '品鉴记录（八维评分 JSONB + 工艺系数，幂等键 user_id+client_id）';
CREATE UNIQUE INDEX uk_tasting_records_user_client ON tasting_records (user_id, client_id);
CREATE INDEX ix_tasting_records_user_id ON tasting_records (user_id);
CREATE INDEX ix_tasting_records_tea_id ON tasting_records (tea_id);
ALTER TABLE tasting_records ADD CONSTRAINT fk_tasting_records_user_id FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE tasting_records ADD CONSTRAINT fk_tasting_records_tea_id FOREIGN KEY (tea_id) REFERENCES teas (id);
ALTER TABLE tasting_records ADD CONSTRAINT fk_tasting_records_ware_id FOREIGN KEY (ware_id) REFERENCES teawares (id);

-- garden_plants（茶园种植，幂等键 user_id + client_id；字段为最小集，待茶园切片确认）
CREATE TABLE garden_plants (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INTEGER NOT NULL,
    client_id  VARCHAR(64) NOT NULL,
    plant_type VARCHAR(50),
    status     VARCHAR(20) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);
COMMENT ON TABLE garden_plants IS '茶园种植（幂等键 user_id+client_id；字段待茶园切片确认回填）';
CREATE UNIQUE INDEX uk_garden_plants_user_client ON garden_plants (user_id, client_id);
ALTER TABLE garden_plants ADD CONSTRAINT fk_garden_plants_user_id FOREIGN KEY (user_id) REFERENCES users (id);

-- agent_prompts（专家 prompt 版本管理，灰度/回滚）
CREATE TABLE agent_prompts (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent      VARCHAR(50) NOT NULL,
    version    VARCHAR(20) NOT NULL,
    content    TEXT NOT NULL,
    status     VARCHAR(20) NOT NULL DEFAULT 'draft',
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);
COMMENT ON TABLE agent_prompts IS 'AI 专家 prompt 版本管理（PRD：agent, version, content, status, created_at）';
CREATE UNIQUE INDEX uk_agent_prompts_agent_version ON agent_prompts (agent, version);

-- ai_usage_logs（AI 调用计量，限流/成本/审计）
CREATE TABLE ai_usage_logs (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INTEGER,
    agent         VARCHAR(50),
    model         VARCHAR(50),
    tokens_in     INTEGER,
    tokens_out    INTEGER,
    latency       INTEGER,
    prompt_version VARCHAR(20),
    created_at    TIMESTAMP NOT NULL DEFAULT now(),
    updated_at    TIMESTAMP NOT NULL DEFAULT now()
);
COMMENT ON TABLE ai_usage_logs IS 'AI 调用计量（PRD：user_id, agent, model, tokens_in, tokens_out, latency, prompt_version；每日统计用 created_at 索引）';
CREATE INDEX ix_ai_usage_logs_created_at ON ai_usage_logs (created_at);
ALTER TABLE ai_usage_logs ADD CONSTRAINT fk_ai_usage_logs_user_id FOREIGN KEY (user_id) REFERENCES users (id);
