-- m5-s2 agent memory V2 迁移（up）
-- 依据：ADR-013（pgvector 混合检索）+ M5 PRD §7（culture_chunks/ai_chat_sessions/ai_messages）
-- 命名规则：ix_{table}_{col} / uk_{table}_{col} / fk_{table}_{col（延续 V1）

-- 1) 扩展：pgvector（向量）+ pg_trgm（关键词相似/模糊加速）
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 2) culture_chunks（文化知识切块；source_type 对应 8 张文化表；embedding 回填由 status 驱动）
CREATE TABLE culture_chunks (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type  VARCHAR(20)  NOT NULL,
    source_id    INTEGER      NOT NULL,
    chunk_text   TEXT         NOT NULL,
    metadata     JSONB        NOT NULL DEFAULT '{}'::jsonb,
    embedding    vector(1024),
    status       VARCHAR(20)  NOT NULL DEFAULT 'pending',
    created_at   TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at   TIMESTAMP    NOT NULL DEFAULT now()
);
COMMENT ON TABLE culture_chunks IS '文化知识切块（M5-S2 混合检索；source_type: tea/person/region/poem/teaware/etiquette/relation/process；embedding 维度对齐 text-embedding-v3）';
CREATE UNIQUE INDEX uk_culture_chunks_source ON culture_chunks (source_type, source_id);
CREATE INDEX ix_culture_chunks_status ON culture_chunks (status);
-- HNSW 向量索引（余弦距离；pgvector ≥0.5）
CREATE INDEX ix_culture_chunks_embedding ON culture_chunks USING hnsw (embedding vector_cosine_ops);
-- pg_trgm GIN 索引（chunk_text 关键词/相似兜底）
CREATE INDEX ix_culture_chunks_text_trgm ON culture_chunks USING gin (chunk_text gin_trgm_ops);

-- 3) ai_chat_sessions（会话头；登录用户专属，游客不落）
CREATE TABLE ai_chat_sessions (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INTEGER      NOT NULL,
    topic      VARCHAR(100),
    agent      VARCHAR(50),
    created_at TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at TIMESTAMP    NOT NULL DEFAULT now()
);
COMMENT ON TABLE ai_chat_sessions IS 'AI 会话头（M5-S2 会话记忆；登录用户专属）';
CREATE INDEX ix_ai_chat_sessions_user_id ON ai_chat_sessions (user_id);
ALTER TABLE ai_chat_sessions ADD CONSTRAINT fk_ai_chat_sessions_user_id FOREIGN KEY (user_id) REFERENCES users (id);

-- 4) ai_messages（消息体；随会话级联删除——用户删除控制权）
CREATE TABLE ai_messages (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id INTEGER      NOT NULL,
    role       VARCHAR(20)  NOT NULL,
    content    TEXT,
    agent      VARCHAR(50),
    tokens     INTEGER,
    created_at TIMESTAMP    NOT NULL DEFAULT now()
);
COMMENT ON TABLE ai_messages IS 'AI 会话消息（M5-S2；级联删除随会话）';
CREATE INDEX ix_ai_messages_session_id ON ai_messages (session_id);
ALTER TABLE ai_messages ADD CONSTRAINT fk_ai_messages_session_id FOREIGN KEY (session_id) REFERENCES ai_chat_sessions (id) ON DELETE CASCADE;
