-- V4: garden-s1 能量事件账本 + garden_plants 扩展（up）
-- 依据：ADR-015（append-only 账本 + 收集聚合）+ garden-product-prd F-G1/G2/G3/G6

-- 1) garden_energy_events：能量事件账本（append-only，幂等 user_id+client_id，防通胀可审计）
CREATE TABLE garden_energy_events (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INTEGER NOT NULL,
    client_id    VARCHAR(64) NOT NULL,
    amount       INTEGER NOT NULL,
    source       VARCHAR(30) NOT NULL,          -- tasting（S1 唯一来源；brew/streak/quest 预留）
    collected_at TIMESTAMP,                     -- NULL=未收；非空=已收集
    created_at   TIMESTAMP NOT NULL DEFAULT now()
);
COMMENT ON TABLE garden_energy_events IS '茶园能量事件账本（append-only，幂等 user_id+client_id，防通胀可审计）';
CREATE UNIQUE INDEX uk_garden_energy_events_user_client ON garden_energy_events (user_id, client_id);
ALTER TABLE garden_energy_events ADD CONSTRAINT fk_garden_energy_events_user_id
    FOREIGN KEY (user_id) REFERENCES users (id);

-- 2) garden_plants 扩展：energy 累计列 + status 语义化（pending 归并为 planted）
ALTER TABLE garden_plants ADD COLUMN energy INTEGER NOT NULL DEFAULT 0;
COMMENT ON COLUMN garden_plants.energy IS '已收集能量累计（浇灌用）';
UPDATE garden_plants SET status = 'planted' WHERE status = 'pending';
ALTER TABLE garden_plants ALTER COLUMN status SET DEFAULT 'planted';
COMMENT ON COLUMN garden_plants.status IS '阶段：planted 种下 / growing 生长 / blooming 开花 / harvested 收获';
