-- m5-s2 V3 迁移（up 副本，与 backend/src/main/resources/db/migration/V3__agent_memory.sql 一致）
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE culture_chunks (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type  VARCHAR(20)  NOT NULL,
    source_id    INTEGER      NOT NULL,
    chunk_text   TEXT         NOT NULL,
    metadata     JSONB        NOT NULL DEFAULT '{}'::jsonb,
    embedding    vector(1024),
    status       VARCHAR(20)  NOT NULL DEFAULT 'pending',
    created_at   TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at   TIMESTAMP    NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uk_culture_chunks_source ON culture_chunks (source_type, source_id);
CREATE INDEX ix_culture_chunks_status ON culture_chunks (status);
CREATE INDEX ix_culture_chunks_embedding ON culture_chunks USING hnsw (embedding vector_cosine_ops);
CREATE INDEX ix_culture_chunks_text_trgm ON culture_chunks USING gin (chunk_text gin_trgm_ops);

CREATE TABLE ai_chat_sessions (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INTEGER      NOT NULL,
    topic      VARCHAR(100),
    agent      VARCHAR(50),
    created_at TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at TIMESTAMP    NOT NULL DEFAULT now()
);
CREATE INDEX ix_ai_chat_sessions_user_id ON ai_chat_sessions (user_id);
ALTER TABLE ai_chat_sessions ADD CONSTRAINT fk_ai_chat_sessions_user_id FOREIGN KEY (user_id) REFERENCES users (id);

CREATE TABLE ai_messages (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id INTEGER      NOT NULL,
    role       VARCHAR(20)  NOT NULL,
    content    TEXT,
    agent      VARCHAR(50),
    tokens     INTEGER,
    created_at TIMESTAMP    NOT NULL DEFAULT now()
);
CREATE INDEX ix_ai_messages_session_id ON ai_messages (session_id);
ALTER TABLE ai_messages ADD CONSTRAINT fk_ai_messages_session_id FOREIGN KEY (session_id) REFERENCES ai_chat_sessions (id) ON DELETE CASCADE;
