-- 运行时领域技能迁移（up，与 V6__agent_skills.sql 一致；依据 ADR-017）
CREATE TABLE agent_skills (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent      VARCHAR(50) NOT NULL,
    domain     VARCHAR(50) NOT NULL,
    skill      TEXT NOT NULL,
    status     VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uk_agent_skills_agent_domain ON agent_skills (agent, domain);

INSERT INTO agent_skills (agent, domain, skill) VALUES
('librarian', 'teaware', '回答茶器问题时：区分器物名称/材质/历史用途，优先引用知识库茶器条目；不确定的窑口与年代标“待核实”。'),
('librarian', 'poem',    '回答茶诗问题时：引用原句时核对诗名与作者；说明创作背景时基于知识库，未命中标注“待核实”。'),
('librarian', 'region',  '回答产区问题时：说明地理与工艺特征；茶类归属按六大茶类口径（tea-tasting 基准），不编造产区产量。'),
('librarian', 'person',  '回答茶人问题时：区分生平/著作/逸事；无知识库依据时只答常识部分并标注“待核实”。');
